<template><div><h1 id="其他" tabindex="-1"><a class="header-anchor" href="#其他" aria-hidden="true">#</a> 其他</h1>
<h3 id="any类型污染问题" tabindex="-1"><a class="header-anchor" href="#any类型污染问题" aria-hidden="true">#</a> any类型污染问题</h3>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">s</span><span style="color: #ABB2BF">:</span><span style="color: #E5C07B">any</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">&#39;string&#39;</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">n</span><span style="color: #ABB2BF">:</span><span style="color: #E5C07B">number</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #E06C75">n</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">s</span><span style="color: #ABB2BF">; </span><span style="color: #7F848E; font-style: italic">// 不报错</span></span>
<span class="line"><span style="color: #E06C75">n</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">*</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">123</span><span style="color: #ABB2BF"> </span><span style="color: #7F848E; font-style: italic">// 不报错</span></span>
<span class="line"><span style="color: #E5C07B">n</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">toFixed</span><span style="color: #ABB2BF">() </span><span style="color: #7F848E; font-style: italic">// 不报错</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在上方代码中,<code v-pre>any</code>类型的<code v-pre>s</code>污染<code v-pre>number</code>类型的<code v-pre>n</code></p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">s1</span><span style="color: #ABB2BF">:</span><span style="color: #E5C07B">unknown</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">&#39;string&#39;</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">n1</span><span style="color: #ABB2BF">:</span><span style="color: #E5C07B">number</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #E06C75">n1</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">s1</span><span style="color: #ABB2BF">; </span><span style="color: #7F848E; font-style: italic">// 不能将类型“unknown”分配给类型“number”</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>可以将<code v-pre>unknow</code>视为为严格版<code v-pre>any</code>,它不会类型污染</p>
</div></template>


