<template><div><h1 id="基础篇" tabindex="-1"><a class="header-anchor" href="#基础篇" aria-hidden="true">#</a> 基础篇</h1>
<h2 id="环境搭建" tabindex="-1"><a class="header-anchor" href="#环境搭建" aria-hidden="true">#</a> 环境搭建</h2>
<p>在一个数据库软件中可以包含多个数据仓库，每个数据仓库可以包含多个数据集合，每个数据集合可以包含多条具体数据</p>
<table>
<thead>
<tr>
<th style="text-align:center">术语</th>
<th style="text-align:center">解释说明</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center">database</td>
<td style="text-align:center">数据库，mongoDB数据库软件可以建立多个数据库</td>
</tr>
<tr>
<td style="text-align:center">collection</td>
<td style="text-align:center">集合，一组数据的集合，可以理解为javascript中的数组</td>
</tr>
<tr>
<td style="text-align:center">document</td>
<td style="text-align:center">文档，一条具体的数据，可以理解为javascript中的对象</td>
</tr>
<tr>
<td style="text-align:center">field</td>
<td style="text-align:center">字段，文档中的属性名称，可以理解为javascript中的对象属性</td>
</tr>
</tbody>
</table>
<h2 id="基本指令" tabindex="-1"><a class="header-anchor" href="#基本指令" aria-hidden="true">#</a> 基本指令</h2>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">show </span><span style="color: #98C379">dbs</span></span>
<span class="line"><span style="color: #ABB2BF">show </span><span style="color: #98C379">database</span></span>
<span class="line"><span style="color: #ABB2BF">// </span><span style="color: #98C379">显示当前所有数据库</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">use </span><span style="color: #98C379">数据库名</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">//</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">进入到指定的数据库中</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">db </span><span style="color: #98C379">//</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">显示当前数据库</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">show </span><span style="color: #98C379">collections</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">//</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">显示数据库中所有集合</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="数据库crud操作" tabindex="-1"><a class="header-anchor" href="#数据库crud操作" aria-hidden="true">#</a> 数据库CRUD操作</h2>
<p>-向数据库中插入文档</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">插入文档</span></span>
<span class="line"><span style="color: #ABB2BF">db.collection..insert(doc)</span></span>
<span class="line"><span style="color: #ABB2BF">    -向集合中插入文档</span></span>
<span class="line"><span style="color: #ABB2BF">    -例如，向test数据库中的stus集合中插入一个新的学生对象</span></span>
<span class="line"><span style="color: #ABB2BF">        {name:&quot;小明&quot;,age:18,gender:&quot;男&quot;}</span></span>
<span class="line"><span style="color: #ABB2BF">        db.</span><span style="color: #56B6C2">test</span><span style="color: #ABB2BF">.insert({name:&quot;小明&quot;,age:18,gender:&quot;男&quot;})</span></span>
<span class="line"><span style="color: #ABB2BF">        当插入文档时，如果没有指定id则数据库会为文档自动添加id，该属性用来作为文档唯一表示</span></span>
<span class="line"><span style="color: #ABB2BF">        id值可以自己指定，数据库不会自动添加，但必须确保id的唯一性</span></span>
<span class="line"><span style="color: #61AFEF">db.collection.insertOne</span><span style="color: #ABB2BF">() // 插入一个</span></span>
<span class="line"><span style="color: #61AFEF">db.collection..insertMany</span><span style="color: #ABB2BF">() // 插入多个</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">查询文档</span></span>
<span class="line"><span style="color: #61AFEF">db.collection..find</span><span style="color: #ABB2BF">() // 返回数组</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #61AFEF">find</span><span style="color: #ABB2BF">()查询集合中符合条件的文档</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #61AFEF">find</span><span style="color: #ABB2BF">()可以接收一个对象作为条件参数</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #61AFEF">find().count</span><span style="color: #ABB2BF">()查询文档数量</span></span>
<span class="line"><span style="color: #ABB2BF">        {}查询集合中所有文档</span></span>
<span class="line"><span style="color: #ABB2BF">        {_id:&quot;hello&quot;}查询id为hello的文档</span></span>
<span class="line"><span style="color: #ABB2BF">db.collection..findOne </span><span style="color: #98C379">//</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">返回对象</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">后可接属性</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #61AFEF">findOne</span><span style="color: #ABB2BF">()查询集合中符合条件的第一个文档</span></span>
<span class="line"><span style="color: #ABB2BF">  </span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">修改文档</span></span>
<span class="line"><span style="color: #ABB2BF">db.collection.update(查询条件，新对象)</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #61AFEF">updata</span><span style="color: #ABB2BF">()默认使用新对象替换旧对象</span></span>
<span class="line"><span style="color: #ABB2BF">    如果需要修改指定属性而不是替换，需要使用修改操作符来修改</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">$set</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">可以用来修改某一属性</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">$unset</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">删除某一属性</span></span>
<span class="line"><span style="color: #ABB2BF">db.</span><span style="color: #56B6C2">test</span><span style="color: #ABB2BF">.update(</span></span>
<span class="line"><span style="color: #ABB2BF">    {</span><span style="color: #98C379">&quot;_id&quot;</span><span style="color: #ABB2BF">:ObjectId(</span><span style="color: #98C379">&quot;611cb3b14424dff2c9c6e884&quot;</span><span style="color: #ABB2BF">)},</span></span>
<span class="line"><span style="color: #ABB2BF">    {</span><span style="color: #E06C75">$set</span><span style="color: #ABB2BF">:{</span></span>
<span class="line"><span style="color: #ABB2BF">    name:&quot;qianba&quot;</span></span>
<span class="line"><span style="color: #ABB2BF">        },</span></span>
<span class="line"><span style="color: #ABB2BF">    }</span></span>
<span class="line"><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">db.collection.updataOne()</span></span>
<span class="line"><span style="color: #ABB2BF">db.collection.updataMany()</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">删除</span></span>
<span class="line"><span style="color: #61AFEF">db.collection.remove</span><span style="color: #ABB2BF">() // 删除一个或多个，默认删除多个</span></span>
<span class="line"><span style="color: #ABB2BF">db.collection.remove({xxx},</span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">) // 删除一个</span></span>
<span class="line"><span style="color: #ABB2BF">db.collection.remove({}) // 清空集合，一个一个删</span></span>
<span class="line"><span style="color: #61AFEF">db.collection.removeOne</span><span style="color: #ABB2BF">() // 删除一个</span></span>
<span class="line"><span style="color: #61AFEF">db.collection.removeMany</span><span style="color: #ABB2BF">() // 删除多个</span></span>
<span class="line"></span>
<span class="line"><span style="color: #61AFEF">db.collection.drop</span><span style="color: #ABB2BF">() // 删除集合</span></span>
<span class="line"><span style="color: #61AFEF">db.dropDatabase</span><span style="color: #ABB2BF">() // 删除数据库</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="增删改查" tabindex="-1"><a class="header-anchor" href="#增删改查" aria-hidden="true">#</a> 增删改查</h2>
<h3 id="创建集合" tabindex="-1"><a class="header-anchor" href="#创建集合" aria-hidden="true">#</a> 创建集合</h3>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #abb2bf">创建集合分为两步，一是对集合设定规则，二是创建集合，创建mongoose.Schema构造函数的实例即可创建集合</span></span>
<span class="line"><span style="color: #abb2bf"></span></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">//设定集和规则</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">courseSchema</span><span style="color: #56B6C2">=</span><span style="color: #C678DD">new</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">Schema</span><span style="color: #ABB2BF">({</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">:</span><span style="color: #E06C75">String</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">author</span><span style="color: #ABB2BF">:</span><span style="color: #E06C75">String</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">isPublished</span><span style="color: #ABB2BF">:</span><span style="color: #E06C75">Boolean</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"></span>
<span class="line"><span style="color: #7F848E; font-style: italic">//创建集合并应用规则</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Course</span><span style="color: #56B6C2">=</span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">model</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;Course&#39;</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">courseSchema</span><span style="color: #ABB2BF">)</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="创建文档" tabindex="-1"><a class="header-anchor" href="#创建文档" aria-hidden="true">#</a> 创建文档</h3>
<p>创建文档实际上就是相机和中插入数据</p>
<p>分为两步</p>
<ol>
<li>
<p>创建集合实例</p>
</li>
<li>
<p>调用实例对象下的save方法将数据保存到数据库中</p>
<p>创建集合实例</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">//创建集合并应用规则</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Course</span><span style="color: #56B6C2">=</span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">model</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;Course&#39;</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">courseSchema</span><span style="color: #ABB2BF">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">course</span><span style="color: #56B6C2">=</span><span style="color: #C678DD">new</span><span style="color: #ABB2BF"> </span><span style="color: #61AFEF">Course</span><span style="color: #ABB2BF">({</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;node.js基础&#39;</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">author</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;黑马&#39;</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">isPublished</span><span style="color: #ABB2BF">:</span><span style="color: #D19A66">true</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 向集合中插入文档</span></span>
<span class="line"><span style="color: #E5C07B">course</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">save</span><span style="color: #ABB2BF">();</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>create方法：返回promise对象（异步）支持异步函数语法</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">//创建集合并应用规则</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Course</span><span style="color: #56B6C2">=</span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">model</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;Course&#39;</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">courseSchema</span><span style="color: #ABB2BF">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #E5C07B">Course</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">create</span><span style="color: #ABB2BF">({</span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;English&#39;</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">author</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;hason&#39;</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">isPublished</span><span style="color: #ABB2BF">:</span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">},(</span><span style="color: #E06C75; font-style: italic">err</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #ABB2BF">)</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// 错误对象</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">err</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// 当前插入的文档</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 异步 Promise</span></span>
<span class="line"><span style="color: #E5C07B">Course</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">create</span><span style="color: #ABB2BF">({</span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;化学&#39;</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">author</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;赵六&#39;</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">isPublished</span><span style="color: #ABB2BF">:</span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">catch</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">err</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">err</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="mongodb数据库导入数据" tabindex="-1"><a class="header-anchor" href="#mongodb数据库导入数据" aria-hidden="true">#</a> mongoDB数据库导入数据</h2>
<p>mongoimport -d 数据库名称 -c 集合名称 -file 要导入的文件</p>
</li>
</ol>
<h2 id="数据库中查询文档" tabindex="-1"><a class="header-anchor" href="#数据库中查询文档" aria-hidden="true">#</a> 数据库中查询文档</h2>
<h3 id="find" tabindex="-1"><a class="header-anchor" href="#find" aria-hidden="true">#</a> find</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">// 查询文档</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">//设定集和规则</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">courseSchema</span><span style="color: #56B6C2">=</span><span style="color: #C678DD">new</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">Schema</span><span style="color: #ABB2BF">({</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">:</span><span style="color: #E06C75">String</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">author</span><span style="color: #ABB2BF">:</span><span style="color: #E06C75">String</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">isPublished</span><span style="color: #ABB2BF">:</span><span style="color: #E06C75">Boolean</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 应用规则</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Course</span><span style="color: #56B6C2">=</span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">model</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;Course&#39;</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">CourseSchema</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">//  查询用户集合中所有文档</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">//  Course.find({_id:&#39;60a46a43ea1a6c3838655fdf&#39;}).then(result=&gt;console.log(result);})</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">//  通过下划线_id字段来查找文档</span></span>
<span class="line"><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Course</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">find</span><span style="color: #ABB2BF">({</span><span style="color: #E06C75">_id</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;60a46a43ea1a6c3838655fdf&#39;</span><span style="color: #ABB2BF">}).</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">     </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF"> })</span></span>
<span class="line"><span style="color: #ABB2BF"> .</span><span style="color: #61AFEF">catch</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">err</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">     </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">err</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF"> })</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="findone" tabindex="-1"><a class="header-anchor" href="#findone" aria-hidden="true">#</a> findOne</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">// 返回一条文档，默认返回集合中的第一条文档</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// Course.findOne({name:&#39;李四&#39;}).then(result=&gt;{console.log(result);})</span></span>
<span class="line"><span style="color: #E5C07B">Course</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">findOne</span><span style="color: #ABB2BF">({</span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;李四&#39;</span><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="匹配大于小于-gt-lt" tabindex="-1"><a class="header-anchor" href="#匹配大于小于-gt-lt" aria-hidden="true">#</a> 匹配大于小于 $gt  $lt</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">// 大于小于 $gt 大于 $lt小于</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// User.findOne({age:{$gt:17,$lt:20}}).then(result=&gt;{console.log(result);})</span></span>
<span class="line"><span style="color: #E5C07B">User</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">findOne</span><span style="color: #ABB2BF">({</span><span style="color: #E06C75">age</span><span style="color: #ABB2BF">:{</span><span style="color: #E06C75">$gt</span><span style="color: #ABB2BF">:</span><span style="color: #D19A66">17</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">$lt</span><span style="color: #ABB2BF">:</span><span style="color: #D19A66">20</span><span style="color: #ABB2BF">}})</span></span>
<span class="line"><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="匹配包含-in-做网站搜索-做搜索关键字-在文档里查询" tabindex="-1"><a class="header-anchor" href="#匹配包含-in-做网站搜索-做搜索关键字-在文档里查询" aria-hidden="true">#</a> 匹配包含 $in  （做网站搜索，做搜索关键字，在文档里查询）</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">//包含</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">//User.find({hobbies:{$in:[敲代码]}}).then(result=&gt;{console.log(result);})</span></span>
<span class="line"><span style="color: #E5C07B">User</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">findOne</span><span style="color: #ABB2BF">({</span><span style="color: #E06C75">hobbies</span><span style="color: #ABB2BF">:{</span><span style="color: #E06C75">$in</span><span style="color: #ABB2BF">:[</span><span style="color: #98C379">&#39;踢球&#39;</span><span style="color: #ABB2BF">]}})</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="选择要查询字段-后边表示不想查询的字段-查询字段" tabindex="-1"><a class="header-anchor" href="#选择要查询字段-后边表示不想查询的字段-查询字段" aria-hidden="true">#</a> 选择要查询字段 -后边表示不想查询的字段   （查询字段）</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #E5C07B">User</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">find</span><span style="color: #ABB2BF">().</span><span style="color: #61AFEF">select</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;name age -_id&#39;</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"><span style="color: #ABB2BF">  </span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="将数据按照年龄排序-降序用-将数据排序" tabindex="-1"><a class="header-anchor" href="#将数据按照年龄排序-降序用-将数据排序" aria-hidden="true">#</a> 将数据按照年龄排序 降序用-  （将数据排序）</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #E5C07B">User</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">find</span><span style="color: #ABB2BF">().</span><span style="color: #61AFEF">sort</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;age&#39;</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>跳过数据，限制查询数量   （网站分页）</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #E5C07B">User</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">find</span><span style="color: #ABB2BF">().</span><span style="color: #61AFEF">skip</span><span style="color: #ABB2BF">(</span><span style="color: #D19A66">2</span><span style="color: #ABB2BF">).</span><span style="color: #61AFEF">limit</span><span style="color: #ABB2BF">(</span><span style="color: #D19A66">3</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="删除文档" tabindex="-1"><a class="header-anchor" href="#删除文档" aria-hidden="true">#</a> 删除文档</h2>
<h3 id="删除单个" tabindex="-1"><a class="header-anchor" href="#删除单个" aria-hidden="true">#</a> 删除单个</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">// 查找到一条文档并删除</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 返回删除的文档</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 如果查询匹配到多个文档 那么将会删除第一个文档</span></span>
<span class="line"><span style="color: #E5C07B">User</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">findOneAndDelete</span><span style="color: #ABB2BF">({</span><span style="color: #E06C75">_id</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;60a4cc4fce929341005a2a9c&#39;</span><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="删除多个文档" tabindex="-1"><a class="header-anchor" href="#删除多个文档" aria-hidden="true">#</a> 删除多个文档</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">// 删除多个文档</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 返回值{ n: 6, ok: 1, deletedCount: 6 } n：代表删除了几条数据 ok：代表删除成功</span></span>
<span class="line"><span style="color: #E5C07B">User</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">deleteMany</span><span style="color: #ABB2BF">({})</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="更新文档" tabindex="-1"><a class="header-anchor" href="#更新文档" aria-hidden="true">#</a> 更新文档</h2>
<h3 id="更新单个" tabindex="-1"><a class="header-anchor" href="#更新单个" aria-hidden="true">#</a> 更新单个</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">// User.updateOne({查询条件},{要更改的值}).then(result=&gt;{console.log(result);})</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 返回值 { n: 1, nModified: 1, ok: 1 } n：代表更新几条数据 ok：代表更新成功</span></span>
<span class="line"><span style="color: #E5C07B">User</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">updateOne</span><span style="color: #ABB2BF">({</span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;王二&#39;</span><span style="color: #ABB2BF">},{</span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;张三&#39;</span><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="更新多个" tabindex="-1"><a class="header-anchor" href="#更新多个" aria-hidden="true">#</a> 更新多个</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">// 更新集合中多个文档</span></span>
<span class="line"><span style="color: #E5C07B">User</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">updateMany</span><span style="color: #ABB2BF">({}, { </span><span style="color: #E06C75">age</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">27</span><span style="color: #ABB2BF"> })</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="mongoose验证" tabindex="-1"><a class="header-anchor" href="#mongoose验证" aria-hidden="true">#</a> mongoose验证</h2>
<p>在创建集合规则时，可以设置当前字段的验证规则，验证失败则输入验证失败</p>
<p>自定义错误信息</p>
<ul>
<li>require：true 必传字段</li>
<li>minlength：3字符串最小长度</li>
<li>maxlength：3字符串最大长度</li>
<li>min：2数值最小为2</li>
<li>max：100数值最大为100</li>
<li>enum：['html','css','javascript','node.js']</li>
<li>trim：true 自动去除字符串两边的空格</li>
<li>validate：自定义验证器</li>
<li>default：默认值</li>
</ul>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #61AFEF">require</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;mongoose&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">connect</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;mongodb://localhost/playground&#39;</span><span style="color: #ABB2BF">, { </span><span style="color: #E06C75">useNewUrlParser</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">useUnifiedTopology</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">true</span><span style="color: #ABB2BF"> })</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(() </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;连接数据库成功&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">catch</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">err</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">err</span><span style="color: #ABB2BF">, </span><span style="color: #98C379">&#39;连接数据库失败&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    });</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">postSchema</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">new</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">Schema</span><span style="color: #ABB2BF">({</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">title</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">type</span><span style="color: #ABB2BF">: </span><span style="color: #E06C75">String</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">required</span><span style="color: #ABB2BF">: [</span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">, </span><span style="color: #98C379">&#39;请传入文章标题&#39;</span><span style="color: #ABB2BF">],</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">minlength</span><span style="color: #ABB2BF">: [</span><span style="color: #D19A66">2</span><span style="color: #ABB2BF">, </span><span style="color: #98C379">&#39;文章长度不能小于2&#39;</span><span style="color: #ABB2BF">],</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">maxlength</span><span style="color: #ABB2BF">: [, </span><span style="color: #98C379">&#39;文章长度不能大于5&#39;</span><span style="color: #ABB2BF">],</span></span>
<span class="line"><span style="color: #ABB2BF">    },</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">age</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">type</span><span style="color: #ABB2BF">: </span><span style="color: #E06C75">Number</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">minlength</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">18</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">maxlength</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">100</span></span>
<span class="line"><span style="color: #ABB2BF">    },</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">publishData</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">type</span><span style="color: #ABB2BF">: </span><span style="color: #E06C75">Date</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">default</span><span style="color: #ABB2BF">: </span><span style="color: #E5C07B">Date</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">now</span></span>
<span class="line"><span style="color: #ABB2BF">    },</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">category</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">type</span><span style="color: #ABB2BF">: </span><span style="color: #E06C75">String</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">enum</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #E06C75">values</span><span style="color: #ABB2BF">:[</span><span style="color: #98C379">&#39;html&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #98C379">&#39;css&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #98C379">&#39;javascript&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #98C379">&#39;node.js&#39;</span><span style="color: #ABB2BF">],</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #E06C75">message</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;分类要在一定的范围内&#39;</span></span>
<span class="line"><span style="color: #ABB2BF">        }</span></span>
<span class="line"><span style="color: #ABB2BF">    },</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">author</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">type</span><span style="color: #ABB2BF">: </span><span style="color: #E06C75">String</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">validate</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #61AFEF">validator</span><span style="color: #ABB2BF">: (</span><span style="color: #E06C75; font-style: italic">v</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">                </span><span style="color: #7F848E; font-style: italic">// 返回布尔值</span></span>
<span class="line"><span style="color: #ABB2BF">                </span><span style="color: #7F848E; font-style: italic">// true 成功</span></span>
<span class="line"><span style="color: #ABB2BF">                </span><span style="color: #7F848E; font-style: italic">// false 失败</span></span>
<span class="line"><span style="color: #ABB2BF">                </span><span style="color: #7F848E; font-style: italic">// v 要验证的值</span></span>
<span class="line"><span style="color: #ABB2BF">                </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">v</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">&amp;&amp;</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">v</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">length</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">&gt;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">4</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #ABB2BF">            },</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #7F848E; font-style: italic">// 自定义错误信息</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #E06C75">message</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;传入的值不符合规则&#39;</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">        }</span></span>
<span class="line"><span style="color: #ABB2BF">    }</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Post</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">model</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;Post&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">postSchema</span><span style="color: #ABB2BF">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #E5C07B">Post</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">create</span><span style="color: #ABB2BF">({ </span><span style="color: #E06C75">title</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;aaaaa&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">age</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">50</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">category</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;C#&#39;</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">author</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;a&#39;</span><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">catch</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">error</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// 获取错误信息对象</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">err</span><span style="color: #56B6C2">=</span><span style="color: #E5C07B">error</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">errors</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #C678DD">for</span><span style="color: #ABB2BF">(</span><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">attr</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">in</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">err</span><span style="color: #ABB2BF">){</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">err</span><span style="color: #ABB2BF">[</span><span style="color: #E06C75">attr</span><span style="color: #ABB2BF">][</span><span style="color: #98C379">&#39;message&#39;</span><span style="color: #ABB2BF">]);</span></span>
<span class="line"><span style="color: #ABB2BF">    }</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="集合关联" tabindex="-1"><a class="header-anchor" href="#集合关联" aria-hidden="true">#</a> 集合关联</h2>
<p>通常不同集合的数据之间是有关系的，例如文章信息和用户信息储存在不同的集合中，但文章是某个用户发表的，要查询的文章的所有信息包括发表用户，就需要用到集合关联</p>
<ul>
<li>
<p>使用id对集合进行关联</p>
</li>
<li>
<p>使用方法进行关联集合查询</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">// 需求：将文章与作者关联</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #61AFEF">require</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;mongoose&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">connect</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;mongodb://localhost/playground&#39;</span><span style="color: #ABB2BF">,{ </span><span style="color: #E06C75">useNewUrlParser</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">useUnifiedTopology</span><span style="color: #ABB2BF">:</span><span style="color: #D19A66">true</span><span style="color: #ABB2BF"> })</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(() </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;数据库连接成功&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">catch</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">err</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">err</span><span style="color: #ABB2BF">,</span><span style="color: #98C379">&#39;数据库连接失败&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">    })</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 用户集合规则</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">userSchema</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">new</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">Schema</span><span style="color: #ABB2BF">({</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">type</span><span style="color: #ABB2BF">: </span><span style="color: #E06C75">String</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">require</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">true</span></span>
<span class="line"><span style="color: #ABB2BF">    }</span></span>
<span class="line"><span style="color: #ABB2BF">});</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 文章集合规则</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">postSchema</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">new</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">Schema</span><span style="color: #ABB2BF">({</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">title</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">type</span><span style="color: #ABB2BF">: </span><span style="color: #E06C75">String</span></span>
<span class="line"><span style="color: #ABB2BF">    },</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">author</span><span style="color: #ABB2BF">:{</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #7F848E; font-style: italic">// 存储下划线id地址</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #7F848E; font-style: italic">// id具有特殊的类型</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">type</span><span style="color: #ABB2BF">:</span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">Schema</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">Types</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">ObjectId</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E06C75">ref</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;User&#39;</span></span>
<span class="line"><span style="color: #ABB2BF">    }</span></span>
<span class="line"><span style="color: #ABB2BF">});</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">User</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">model</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;User&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">userSchema</span><span style="color: #ABB2BF">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Post</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">mongoose</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">model</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;Post&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">postSchema</span><span style="color: #ABB2BF">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #7F848E; font-style: italic">//创建用户</span></span>
<span class="line"><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">User</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">create</span><span style="color: #ABB2BF">({</span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;一个用户&#39;</span><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #ABB2BF">     .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">         </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">     })</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 创建文章</span></span>
<span class="line"><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">Post</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">create</span><span style="color: #ABB2BF">({</span><span style="color: #E06C75">title</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;123&#39;</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">author</span><span style="color: #ABB2BF">:</span><span style="color: #98C379">&#39;60a52939d0dc740f009c0e0f&#39;</span><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #ABB2BF">     .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">         </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">     })</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 查询</span></span>
<span class="line"><span style="color: #E5C07B">Post</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">find</span><span style="color: #ABB2BF">().</span><span style="color: #61AFEF">populate</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;author&#39;</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">    .</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">result</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">console</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">log</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">result</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="案例-用户信息增删改查" tabindex="-1"><a class="header-anchor" href="#案例-用户信息增删改查" aria-hidden="true">#</a> 案例：用户信息增删改查</h2>
<p>1.搭建网站服务器，实现客户端与服务器端的通信
2.连接数据库， 创建用户集合，向集合中插入文档
3.当用户访问/list时,将所有用户信息查询出来
4.将用户信息和表格HTML进行拼接并将拼接结果响应回客户端
5.当用户访问/add时， 呈现表郸面，并实现添加用户信息功能
6.当用户访问/modify时， 呈现修改页面，并实现修改用户信息功能
7.当用户访问/delete时, 实现用户删除功能</p>
</li>
</ul>
<h2 id="第三方模块-router" tabindex="-1"><a class="header-anchor" href="#第三方模块-router" aria-hidden="true">#</a> 第三方模块 router</h2>
<p>功能：实现路由</p>
<p>使用步骤：</p>
<ol>
<li>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #abb2bf">获取路由对象</span></span>
<span class="line"><span style="color: #abb2bf"></span></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></li>
<li>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #abb2bf">调用路由对象提供的方法创建路由</span></span>
<span class="line"><span style="color: #abb2bf"></span></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></li>
<li>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #abb2bf">启用路由，使路由生效</span></span>
<span class="line"><span style="color: #abb2bf"></span></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></li>
</ol>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">getRouter</span><span style="color: #56B6C2">=</span><span style="color: #61AFEF">require</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;router&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">router</span><span style="color: #56B6C2">=</span><span style="color: #61AFEF">getRouter</span><span style="color: #ABB2BF">();</span></span>
<span class="line"><span style="color: #E5C07B">router</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">get</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;/add&#39;</span><span style="color: #ABB2BF">,(</span><span style="color: #E06C75; font-style: italic">req</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75; font-style: italic">res</span><span style="color: #ABB2BF">)</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">	</span><span style="color: #E5C07B">res</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">end</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;hello world&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #E5C07B">sever</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">on</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;request&#39;</span><span style="color: #ABB2BF">,(</span><span style="color: #E06C75; font-style: italic">req</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75; font-style: italic">res</span><span style="color: #ABB2BF">)</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #61AFEF">router</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">req</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">res</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="第三方模块server-static" tabindex="-1"><a class="header-anchor" href="#第三方模块server-static" aria-hidden="true">#</a> 第三方模块server-static</h2>
<p>功能：实现静态资源访问服务</p>
<p>步骤：</p>
<ol>
<li>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #abb2bf">引入server-static模块获取创建静态资源服务功能的方法</span></span>
<span class="line"><span style="color: #abb2bf"></span></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></li>
<li>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #abb2bf">调用方法创建静态资源并指定静态资源服务目录</span></span>
<span class="line"><span style="color: #abb2bf"></span></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></li>
<li>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #abb2bf">启用静态资源服务功能</span></span>
<span class="line"><span style="color: #abb2bf"></span></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></li>
</ol>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">serverStatic</span><span style="color: #56B6C2">=</span><span style="color: #61AFEF">require</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;server-static&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">serve</span><span style="color: #56B6C2">=</span><span style="color: #61AFEF">serveStatic</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;public&#39;</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #E5C07B">sever</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">on</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;request&#39;</span><span style="color: #ABB2BF">,(</span><span style="color: #E06C75; font-style: italic">req</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75; font-style: italic">res</span><span style="color: #ABB2BF">)</span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #61AFEF">server</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">req</span><span style="color: #ABB2BF">,</span><span style="color: #E06C75">res</span><span style="color: #ABB2BF">);</span></span>
<span class="line"><span style="color: #ABB2BF">})</span></span>
<span class="line"><span style="color: #E5C07B">sever</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">listen</span><span style="color: #ABB2BF">(</span><span style="color: #D19A66">3000</span><span style="color: #ABB2BF">);</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


